services:
  db:
    image: postgres:15.0-alpine

    container_name: 'book-db'

    expose:
      - "5432"

    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
      - ../db/database:/var/lib/postgresql/data
      - ../db/init:/docker-entrypoint-initdb.d

    
  web:
    image: django/web:1.0

    build: ./web

    container_name: 'book-web'

    expose:
      - "8080"

    environment:
      - DEBUG=1
    
    depends_on:
      - db
    
    stdin_open: true

    tty: true

    #uswgiのコマンド追加
    command: uwsgi --socket :8080 --module app.wsgi --chdir /home/user1/book

    volumes:
      - ../web:/home/user1/book
      - ../web/static:/static
    

  #nginx追加

  nginx:
    image: nginx:latest

    ports:
      - "80:80"

    volumes:
      - ../nginx/conf:/etc/nginx/conf.d
      - ../nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ../web/static:/static
    
    depends_on:
     - web
  

#https-portal追加
#  https-portal:
#    image: steveltn/https-portal:1
#    
#    ports:
#      - "80:80"
#      - "443:443"

#    restart: always

#    depends_on:
#      - nginx

#    environment:
#      DOMAINS: 'localhost -> http://nginx:80'
#      STAGE: 'local'
#FORSE_RENEW: 'true'
    
#    volumes:
#      - ../nginx/ssl_certs:/var/lib/https-portal