services:
  db:
    image: postgres:15.0-alpine

    container_name: 'book-db'

    expose:
      - "5432"

    environment:
      - TZ=Asia/Tokyo
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

    volumes:
      - ../db/database:/var/lib/postgresql/data
      - ../db/init:/docker-entrypoint-initdb.d

    
  web:
    image: django/web:1.0

    build: ./web

    container_name: 'book-web'

    ports:
      - "8080:8080"

    environment:
      - DEBUG=1
    
    depends_on:
      - db
    
    stdin_open: true

    tty: true

    #uswgiのコマンド追加
    command: uwsgi --socket :8080 --module app.wsgi --chdir /home/user1/book

    volumes:
      - ../web:/home/user1/book
      - ../web/static:/static
    

#nginx追加

  nginx:
    image: nginx:latest

    ports:
      - "80:80"
    
    volumes:
      - ../nginx/:/etc/nginx/conf.d
      - ../nginx/uwsgi_params:/etc/nginx/uwsgi_params
      - ../web/static:/static
    
    depends_on:
      - web